wd: /UDITAS/WORKDIR
blacklist_dir: 00.blacklist
fastq_dir: 00.fastq
donor_map_dir: 00.donor_map
genome_dir: 00.genome
donor_check_dir: 00.donor_check
clean_dir: 01.clean
trimmed_dir: 02.trimmed
donor_aligned_dir: 03.donor_align
donor_check_aligned_dir: 03.donor_check_align
human_aligned_dir: 03.human_align
read_analysis_dir: 04.read_analysis
junction_reads_dir: 05.junction_reads
donor_reads_dir: 05.donor_reads
human_both_aligned_dir: 06.human_both_align
donor_both_aligned_dir: 06.donor_both_align
mgefinder_dir: 07.mgefinder
kmer_flanks_dir: 08.kmer_flanks
umi_counts_dir: 09.umi_counts
raw_counts_dir: 09.raw_counts
target_sites_dir: 10.target_sites
results_dir: 11.results
